version: "2.29.0"

services:
  translator-service:
    container_name: translator-service-container
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - backend

  postgresql:
    image: postgres:16
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:${POSTGRES_PORT}/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    volumes:
      - ./src/main/resources/db/changelog/:/liquibase/changelog/
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }