# Project building
FROM gradle:jdk21 AS BUILD
WORKDIR /usr/app
COPY . .
RUN gradle build -x test



# Container
FROM openjdk:21
ENV JAR_NAME=translator-0.0.1-SNAPSHOT.jar
ENV APP_HOME=/usr/app
WORKDIR $APP_HOME
COPY --from=BUILD $APP_HOME .
ENTRYPOINT exec java -jar $APP_HOME/build/libs/$JAR_NAME