spring:
  application:
    name: translator
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/master.yaml

app:
  yandex-translate-url: ${YANDEX_TRANSLATE_URL}
  yandex-detect-language-url: ${YANDEX_DETECT_LANGUAGE_URL}
  yandex-api-key: ${YANDEX_API_KEY}
  threads-number: 10

springdoc:
  api-docs:
    path: /api-docs
